"""Paths and study constants."""

from __future__ import annotations

from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
# Identical to radiomics/processed/manifests/experiment_index.csv regenerated by `main.py prep-data`.
EXPERIMENT_INDEX = REPO / "reference-processed" / "manifests" / "experiment_index.csv"
LEGACY_FEATURES_DIR = REPO / "reference-processed" / "postoperative_progression_surveillance" / "features"
OUTPUTS = REPO / "outputs"

HORIZONS = (90, 120, 180)
PRIMARY_HORIZON = 120
EARLY_POST_RT_DAYS = 84  # RANO 2.0: first 12 weeks after radiotherapy
N_REPEATS = 5
N_FOLDS = 5

# MU-Glioma-Post mask labels (verified with BraTS zero-shot: ET <-> label 3).
LABEL_NETC, LABEL_SNFH, LABEL_ET, LABEL_RC = 1, 2, 3, 4
